#language: python
#python:
#  - 3.6
#install:
#  - pip install -q pipenv codecov
#  - pipenv sync --dev
#script:
#  - flake8
#  - pytest libpythonjp --cov = libpythonjp
#env:
#  - CODECOV_TOKEN = 456f2bf2-ac0d-42de-ab61-3d69a617ce0b
#after_success:
#  - codecov
